### ISSUE TITLE
Media uploaded successfully on previous day shown as processing when we access the app next day

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#493]
**Describe the bug**

When we upload media on the previous day successfully, and then access the app next day, the media uploaded on previous days shows as processing onoy

1. Go to Save App
2. Upload few images / videos 
3. After uploading the images / videos successfully, access the app next day

**Expected behavior**
Images / videos uploaded on previous day should be visible on next day

Actual Result : 

Media uploaded on previous day shown as processing when we access the app next day

Below is the video : 

https://github.com/OpenArchive/Save-app-android/assets/8190141/996629f3-8499-4703-8907-cacee34b8345

**Environment (please complete the following information):**
 - OS version: Android 11, Android 13
 - Device: Samsung Galaxy A70, Samsung Galaxy A13
 - App Version : 0.3.0-alpha5

**Additional context**

**Comment by foundscapes** [comment]
Another issue that will hopefully be resolved with the ux updates? @tladesignz

**Comment by tladesignz** [comment]
@purvi-ranawat, so much has changed now. Please test again with latest deployed version! Thank you!

**Comment by foundscapes** [comment]
@purvi-ranawat please test asap, ty!

**Comment by purvi-ranawat** [comment]
@foundscapes : The issue still exists on 0.3.0-beta5. Currently I have beta6 installed and will test in it. But I will get the results till tomorrow as I have to wait for a day to check the issue

**Comment by foundscapes** [comment]
@vanichitkara can you please test to see if this is happening for you too?

**Comment by vanichitkara** [comment]
@foundscapes I tested this, and it's not happening with me. The media did not show up as being processed. 
OS version: Android v13.0
Device: OnePlus 11R 5G
App Version 0.3.0-beta6
