### ISSUE TITLE
Full sentence not showing up in the modal before uploading media

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#527]
**Describe the bug**
When trying to upload media, the modal before the upload starts has the text cut and doesn't show the full sentence. Also, the text size looks big on the screen; the text could be shorter. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a folder and select some media to upload
2. The screen will appear

**Expected behavior**
Expected behaviour is that the sentence should not be cut off and should be fully visible. 

**Screenshots**
![Screenshot_2023-11-04-17-43-34-58_0ee13e842c552dd3714f8967301299aa](https://github.com/OpenArchive/Save-app-android/assets/64951124/2815fdcd-859d-4643-b2ad-71dd90bee6af)

**Environment**
OS version: Android v13.0
Device: OnePlus 11R 5G
App Version 0.3.0-beta7

**Additional context**

**Comment by foundscapes** [comment]
Not happening for two of us on OS 11 and 12 - @purvi-ranawat please test on OS 13 ty!

**Comment by purvi-ranawat** [comment]
@foundscapes : The issue exists for me also on Android 13 OS

Below is the screenshot : 

![full sentence not shown](https://github.com/OpenArchive/Save-app-android/assets/8190141/de3f2eb9-470d-4299-838e-34a5bb088dcc)

Environment : 
OS ; Android 13
Device : Samsung Galaxy S23 FE
Build version : 0.3.0-beta8

**Comment by foundscapes** [comment]
ty @purvi-ranawat~ @uniqx this seems like it's an android OS 13 issue, is there anything you can do to ensure the language shows up on that platform/across all platforms? ty!

**Comment by uniqx** [comment]
After a little debugging I think this issue is dependent on the screen size, and font-size settings. I've implemented a fix where I change `maxLines` from Androids default value (2) to 99.

659771b

**Comment by ceylana** [comment]
@purvi-ranawat and @vanichitkara can you test to see if this is resolved please?

**Comment by purvi-ranawat** [comment]
@ceylana / @foundscapes : I have tested the same on Android 13 and it is working fine now.

Environment : 
OS : Android 13
Device : Samsung Galaxy A13
Build Version : 0.3.0

**Comment by vanichitkara** [comment]
@foundscapes I'm still facing this issue 
Environment
OS version: Android v13.0
Device: OnePlus 11R 5G
App Version 0.3.1-alpha2

**Comment by ryjen** [comment]
That does not look like a proper title in the screen shot anyway.  Can we use a more concise title (uploads) and put that string into the description below it? @uniqx
